# Generated by Django 4.2.5 on 2023-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('female', 'Feminino'), ('male', 'Masculino'), ('female', 'Feminino'), ('others', 'Outros'), ('none', 'Prefiro não dizer')], max_length=10)),
            ],
        ),
    ]
